### PR TITLE
Building tribute page

### PR DESCRIPTION
**Pull request by Najeeba-Qarqin**
{5DDC2D34-506F-4BD5-96B6-0BD9F32627EA} png

This is a tribute page for "Mark Zuckerberg " ,build by using HTML and  styled by using CSS.

### CODE REVIEW

**Comment by Najeeba-Qarqin** [comment]
@ahzamir This is the tribute page project sir ready to review!

**Comment by Najeeba-Qarqin** [comment]
@ahzamir waiting for your feedback :D

**Comment by Najeeba-Qarqin** [comment]
@zainab73629 Please give me your feedback.

**Review by ahzamir — APPROVED** [review]
### Hi @Najeeba-Qarqin 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳
ExcellentNiceGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Tribute Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Najeeba-Qarqin** [comment]
@ahzamir should I merge the PR?
And I didn't use Facebook and LinkedIn yet I don't know how to post or share something. 🤷‍♀️🤦🏻‍♀️

**Pull request merged**
